## The following functions compute, cache, and retrieve the inverse of a matrix.

## makeCacheMatrix takes an invertible matrix as an input an returns a list of functions that set and retrieve the input
## matrix and it's inverse (if it has been computed and cached).

makeCacheMatrix <- function(x = matrix()) {         #Input default is an empty matrix
  m <- matrix()                                     #Set inverse, m, to an emptry matrix
  set <- function(y) {                              #set function reinitializes x and m in makeCacheMatrix(x) env. 
    x <<- y
    m <<- matrix()
  }
  get <- function() x                               #get function retrieves x
  setinverse <- function(inverse) m <<- inverse     #setinverse function assigns inverse to m in makeCacheMatrix(x) env.
  getinverse <- function()  m                       #getinverse function retrieves m (an empty matrix or inverse of x)
  list(set = set, get = get,                        #list of functions used to assign and cache a matrix and its inverse
       setinverse = setinverse,
       getinverse = getinverse)
}


## cacheSolve takes the output generated by makeCacheMatrix and either retrieves the cached inverse of the matrix
## (if it exists) or calculates the inverse and caches it in makeCacheMatrix.

cacheSolve <- function(x, ...) {                #Input is the output of makeCacheMatrix for the matrix under consideration
  b <- x$getinverse()                           #Assigns the inverse matrix in makeCacheMatrix to b
  if(!is.na(det(b))){                           #Using determinant to determine if b is an empty matrix
    message("Getting cached inverse...")        #If det(b) returns a value, there is a cached inverse matrix
    return(b)                                   #Retrieve cached inverse
  }
  data <- x$get()                               #If no cache inverse, assign the original matrix to data
  m <- solve(data, ...)                         #Compute inverse of data and assign to m
  x$setinverse(m)                               #Call the setinverse function in x and pass the inverse, m, to update the cache
  m                                             #Print the inverse
}
